/**
 *
 * @author ruhithomas
 * DATE:14 April 2020
 * COURSE:CS206 Object Oriented and Design Programming
 * 
 * DESCRIPTION:
 * contains code for the user to search others research by topic or year
 * 
 * @note change line 257,338 to connect to database
 */

package research;

import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

public class otherswork extends javax.swing.JFrame {

    /**
     * Creates new form otherswork
     */
    public otherswork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_year = new javax.swing.JTextField();
        jTextField_topic = new javax.swing.JTextField();
        jButton_year = new javax.swing.JButton();
        jButton_topic = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel1.setText("Enter year");

        jLabel2.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jLabel2.setText("Enter topic");

        jButton_year.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButton_year.setText("SEARCH BY YEAR");
        jButton_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_yearActionPerformed(evt);
            }
        });

        jButton_topic.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButton_topic.setText("SEARCH BY TOPIC");
        jButton_topic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_topicActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButton1.setText("GO TO MY RESEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Futura", 0, 14)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" FACILITY SYSTEM");

        jLabel6.setFont(new java.awt.Font("Futura", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("101");

        jLabel7.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RESEARCH ARTEFACT ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        jLabel3.setText("101 RESEARCH DATABASE");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("You have permission to view others research work");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_topic, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_topic, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_year, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_year))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_topic))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /* Function which returns ArrayList containing name,topic,year,filepath of selected year */
     public ArrayList<User> userList_year(){
        System.out.print("I'm in userlist");
        ArrayList<User> usersList=new ArrayList<>();
        try{
            
        Connection con;
        //connecting to database
        con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/researchartefact", "root", "light123hash");
//        Statement stmt = con.createStatement();
////        String uname=jLabel_Username.getText();
////        String uname="Peter Pan";
//        String sql = "SELECT id FROM researchartefact.researcher WHERE username='"+Globals.uname+"'";
//        System.out.print("uname is "+Globals.uname);
//        System.out.print("query is "+sql);
//        ResultSet result = stmt.executeQuery(sql);
//        
//        if(result.next())
//            {
//                int id = result.getInt("id");
//                System.out.print("ID:"+id);
//                String query="SELECT workId FROM researchartefact.researchwork WHERE researcherId="+id;
//                Statement st=con.createStatement();
//                ResultSet rs = st.executeQuery(query);
                
                //rs gives u all the workId...we have 11 and 13
//                System.out.print("\n@**"+rs.getString(1)+"**");
//                System.out.print("\n@**"+rs.getString(2)+"**");
//                while(rs.next())
//                {
//                    System.out.print("**"+rs.getString(i)+"**");
                    String query2;
                    //search  by year
                    query2="SELECT r.username,w.topic,w.year,f.filelocation FROM researchartefact.fileinfo f, researchartefact.researcher r ,researchartefact.researchwork w WHERE f.workId=w.workId AND w.researcherId=r.id AND w.year="+jTextField_year.getText();
              
                    Statement st2=con.createStatement();
                    ResultSet rs2 = st2.executeQuery(query2);
//                    select filename, topic,year,filepath
                     User user;
                     while(rs2.next())
                     {
                        user=new User(rs2.getString(1),rs2.getString(2),rs2.getInt(3),rs2.getString(4)); 
                        usersList.add(user);
                     }
//                     System.out.print("\nok...i reached end of loop for 11");
//                }
//            }
        
        }
        
        catch(SQLException ex){
            
             Logger.getLogger(superior.class.getName()).log(Level.SEVERE, null, ex);
       }
        return usersList; 
    }
    
    /* Function to insert details of user's name,topic,year,filepath into Object data and call table display function */
    public void show_user_year(){
//    System.out.print("I'm in show user");
        ArrayList<User>list=userList_year();
        DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
        
        Object[][] data = new Object[list.size()][4];
        for(int i=0;i<list.size();i++)
        {
             data[i][0]=list.get(i).getusername();
             data[i][1]=list.get(i).gettopic();
             data[i][2]=list.get(i).getyear();
             data[i][3]=list.get(i).getfilepath();
           
        }
//        
//        for(int i=0;i<list.size();i++)
//        {
//             System.out.print("## "+data[i][0]+" ##");
//             System.out.print("## "+data[i][1]+" ##\n");
//           
//        }
        
        ButtonClumn bc=new ButtonClumn(data);
    }
    
    /* Function which returns ArrayList containing name,topic,year,filepath of selected topic */
    public ArrayList<User> userList_topic(){
//        System.out.print("I'm in userlist");
        ArrayList<User> usersList=new ArrayList<>();
        try{
        Connection con;
        con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/researchartefact", "root", "light123hash");
//        Statement stmt = con.createStatement();
////        String uname=jLabel_Username.getText();
////        String uname="Peter Pan";
//        String sql = "SELECT id FROM researchartefact.researcher WHERE username='"+Globals.uname+"'";
//        System.out.print("uname is "+Globals.uname);
//        System.out.print("query is "+sql);
//        ResultSet result = stmt.executeQuery(sql);
//        
//        if(result.next())
//            {
//                int id = result.getInt("id");
//                System.out.print("ID:"+id);
//                String query="SELECT workId FROM researchartefact.researchwork WHERE researcherId="+id;
//                Statement st=con.createStatement();
//                ResultSet rs = st.executeQuery(query);
                
                //rs gives u all the workId...we have 11 and 13
//                System.out.print("\n@**"+rs.getString(1)+"**");
//                System.out.print("\n@**"+rs.getString(2)+"**");
//                while(rs.next())
//                {
//                    System.out.print("**"+rs.getString(i)+"**");
                    String query2;
                 //search year
                     query2="SELECT r.username,w.topic,w.year,f.filelocation FROM researchartefact.fileinfo f, researchartefact.researcher r ,researchartefact.researchwork w WHERE f.workId=w.workId AND w.researcherId=r.id AND w.topic='"+jTextField_topic.getText()+"'";              
                    Statement st2=con.createStatement();
                    ResultSet rs2 = st2.executeQuery(query2);
//                    System.out.print(jTextField_topic.getText());
//                    String filename,String topic,int year,String filepath
                     User user;
                     while(rs2.next())
                     {
                        user=new User(rs2.getString(1),rs2.getString(2),rs2.getInt(3),rs2.getString(4)); 
                        usersList.add(user);
                     }
//                     System.out.print("\nok...i reached end of loop for 11");
                    
                     
//                }
//            }
        
        }
        catch(SQLException ex){
             Logger.getLogger(superior.class.getName()).log(Level.SEVERE, null, ex);
       }
        return usersList; 
    }
    
    /* Function to insert details of user's name,topic,year,filepath into Object data and call table display function */
    public void show_user_topic(){
     
    System.out.print("I'm in show user");
        ArrayList<User>list=userList_topic();
        DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
        Object[][] data = new Object[list.size()][4];
        for(int i=0;i<list.size();i++)
        {
             data[i][0]=list.get(i).getusername();
             data[i][1]=list.get(i).gettopic();
             data[i][2]=list.get(i).getyear();
             data[i][3]=list.get(i).getfilepath();
           
        }
//        
//        for(int i=0;i<list.size();i++)
//        {
//             System.out.print("## "+data[i][0]+" ##");
//             System.out.print("## "+data[i][1]+" ##\n");
//           
//        }
        ButtonClumn bc=new ButtonClumn(data);
    }
  

public class ButtonClumn extends JFrame {
  public ButtonClumn(Object[][] data){
      //COLUMN HEADERS
        String columnHeaders[]={"Name","topic","year","viewfile"};
        //CREATE OUR TABLE AND SET HEADER
        JTable table=new JTable(data,columnHeaders);
       
       //SET CUSTOM RENDERER TO clickme COLUMN
        table.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());;

        //SET CUSTOM EDITOR TO clickme COLUMN
        table.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JTextField()));
        //SCROLLPANE,SET SZE,SET CLOSE OPERATION
//        JScrollPane pane=new JScrollPane(table);
        jScrollPane2.getViewport ().add(table);
//        getContentPane().add(pane);
//        setSize(450,100);

//        setDefaultCloseOperation(EXIT_ON_CLOSE);
      
  }
  
//BUTTON RENDERER CLASS
class ButtonRenderer extends JButton implements  TableCellRenderer
{

  //CONSTRUCTOR
  public ButtonRenderer() {
    //SET BUTTON PROPERTIES
    setOpaque(true);
  }
  @Override
  public Component getTableCellRendererComponent(JTable table, Object obj,
      boolean selected, boolean focused, int row, int col) {

    //SET PASSED OBJECT AS BUTTON TEXT
//      setText((obj==null) ? "":obj.toString());
  setText("VIEW FILE");
    return this;
  }

}

//BUTTON EDITOR CLASS
class ButtonEditor extends DefaultCellEditor
{
  protected JButton btn;
   private String lbl;
   private Boolean clicked;

   public ButtonEditor(JTextField txt) {
    super(txt);

    btn=new JButton();
    btn.setOpaque(true);

    //WHEN BUTTON IS CLICKED
    btn.addActionListener(new ActionListener() {

      @Override
      public void actionPerformed(ActionEvent e) {

        fireEditingStopped();
      }
    });
  }
   
   //OVERRIDE A COUPLE OF METHODS
   @Override
  public Component getTableCellEditorComponent(JTable table, Object obj,
      boolean selected, int row, int col) {

      //SET TEXT TO BUTTON,SET CLICKED TO TRUE,THEN RETURN THE BTN OBJECT
     lbl=(obj==null) ? "":obj.toString();
     btn.setText("VIEW FILE");
     clicked=true;
    return btn;
  }

  //IF BUTTON CELL VALUE CHNAGES,IF CLICKED THAT IS
   @Override
  public Object getCellEditorValue() {

     if(clicked)
      {
      //SHOW US SOME MESSAGE
          //
          //
          try{
            
            Desktop.getDesktop().open(new java.io.File(lbl));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
//        JOptionPane.showMessageDialog(btn, lbl+" Clicked");
      }
    //SET IT TO FALSE NOW THAT ITS CLICKED
    clicked=false;
    return new String(lbl);
  }

   @Override
  public boolean stopCellEditing() {

         //SET CLICKED TO FALSE FIRST
      clicked=false;
    return super.stopCellEditing();
  }

   @Override
  protected void fireEditingStopped() {
    // TODO Auto-generated method stub
    super.fireEditingStopped();
  }
  }
}
    
    
    
    
    
    private void jButton_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_yearActionPerformed

        show_user_year();
        
    }//GEN-LAST:event_jButton_yearActionPerformed

    private void jButton_topicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_topicActionPerformed
        show_user_topic();
    }//GEN-LAST:event_jButton_topicActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.dispose();
                folderchoose mf = new folderchoose();
                mf.setVisible(true);
                mf.pack();
                mf.setLocationRelativeTo(null);
                //mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
             
                researcherpage.jLabel_Username.setText(Globals.uname);
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        signup mf = new signup();
        mf.setLocationRelativeTo(null);
        mf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(otherswork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(otherswork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(otherswork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(otherswork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new otherswork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_topic;
    private javax.swing.JButton jButton_year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_topic;
    private javax.swing.JTextField jTextField_year;
    // End of variables declaration//GEN-END:variables
}
