/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package research;
import javax.swing.JTable;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ruhithomas
 */
public class superior extends javax.swing.JFrame {

    /**
     * Creates new form superior
     */
    public superior() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User> userList(){
        System.out.print("I'm in userlist");
        ArrayList<User> usersList=new ArrayList<>();
        try{
        Connection con;
        con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/researchartefact", "root", "light123hash");
        Statement stmt = con.createStatement();
//        String uname=jLabel_Username.getText();
//        String uname="Peter Pan";
        String sql = "SELECT id FROM researchartefact.researcher WHERE username='"+Globals.uname+"'";
        System.out.print("uname is "+Globals.uname);
        System.out.print("query is "+sql);
        ResultSet result = stmt.executeQuery(sql);
        if(result.next())
            {
                int id = result.getInt("id");
                System.out.print("ID:"+id);
                String query="SELECT username,id FROM researchartefact.researcher WHERE superiorId="+id;
                Statement st=con.createStatement();
                ResultSet rs = st.executeQuery(query);
                User user;
                while(rs.next())
                {
                     user=new User(rs.getString(1),rs.getInt(2)); 
                     usersList.add(user);
                      
                }
            }
        }
        catch(SQLException ex){
             Logger.getLogger(superior.class.getName()).log(Level.SEVERE, null, ex);
       }
        return usersList; 
    }
    
    public void show_user(){
    System.out.print("I'm in show user");
        ArrayList<User>list=userList();
        DefaultTableModel model =(DefaultTableModel)jTable_Display_User.getModel();
        Object[] row = new Object[2];
        for(int i=0;i<list.size();i++)
        {
             row[0]=list.get(i).getusername();
             row[1]=list.get(i).getid();
             model.addRow(row);
        }
    }
//    public void fillStudent(JTable table)
//    {
//        Connection connection;
//        PreparedStatement ps;
//        Statement stmt = null;
//        try{
//            String uname=jLabel_Username.getText();
//        connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/researchartefact", "root", "light123hash");
//        
//         stmt = connection.createStatement();
//            String sql = "SELECT id FROM researchartefact.researcher WHERE username='"+uname+"'";
////            System.out.print(sql);
//            ResultSet result = stmt.executeQuery(sql);
//            
//            if(result.next())
//            {
//                int id = result.getInt("id");
//                ps=connection.prepareStatement("SELECT username,id FROM researchartefact.researcher WHERE superiorId="+id);
//                ResultSet rs=ps.executeQuery();
//                
//                DefaultTableModel model = (DefaultTableModel)table.getModel();
//                
//                Object[] row;
//                
//                while(rs.next())
//                {
//                    row=new Object[2];
//                    row[0]=rs.getString(1);
//                    row[1]=rs.getInt(2);
//                    
//                    model.addRow(row);
//                }
//                
//            }
//        
//        
//        }catch(SQLException ex){
//             Logger.getLogger(superior.class.getName()).log(Level.SEVERE, null, ex);
//       }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME ");

        jLabel2.setText("TO SUPERIOR PAGE!");

        jLabel4.setText("SUBORDINATE WORK LIST");

        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "WORK"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_User);

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        signup mf = new signup();
        mf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(superior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(superior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(superior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(superior.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new superior().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel_Username;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    // End of variables declaration//GEN-END:variables
}
